#[derive(Debug)]
pub struct Config {
    pub header: String,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            header: "/* Auto-generated by cargo-mkrs */".to_owned(),
        }
    }
}

pub fn get_config() -> Config {
    fn inner() -> Option<Config> {
        let mut path = std::env::current_dir().ok()?;
        path.push(".mkrs");

        let src = std::fs::read_to_string(path).ok()?;
        let table: toml::Table = src.parse().ok()?;

        let header = table.get("header")?.as_str()?.to_string();

        Some(Config { header })
    }

    inner().unwrap_or_default()
}
